Beranda/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name = 'home'),
    path('program/',views.program, name = 'program'),
    path('history/',views.history, name = 'history'),

]

TP1/urls.py
from django.contrib import admin

from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Beranda.urls')),
    path('', include('donasi.urls')),
    path('',include('daftar.urls')),
    path('',include('About.urls')),
    path('auth/', include('social_django.urls', namespace = 'social'))

]

donasi/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "donasi"

urlpatterns = [
    path('donatur/', donatur_view, name='donatur'),
    path('postdonasi/', formView, name='post'),
    path('thankyou/', thankyou, name='thankyou'),
    path('donasi/<int:id>/', donasi_view, name='program_donasi'),
]

Beranda/models.py
from django.db import models

# Create your models here.

class Program(models.Model):
     judul_program = models.CharField(max_length = 100)
     isi_program = models.CharField(max_length = 100)
     img_program = models.CharField(max_length = 300)

Beranda/views.py
from django.shortcuts import render
from donasi.models import MyModels
from .models import Program

# Create your views here.
def home(request):
    return render(request, 'home.html')
def program(request):
    programs = Program.objects.all()
    return render(request, 'program.html',{'programs':programs})
def history(request):
    if request.user.is_authenticated:
        result = MyModels.objects.all().filter(nama = request.user.username)
        response = {'data': result}
        return render(request, 'history_page.html',response)
    else:
        return render(request, 'home.html')

Beranda/templates/history_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<hmtl>
	<head>
		<br/>
		<div class="container" style="background-color: #598FB5">
		<!-- bootstrap using cdn -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<!-- responsive for mobile -->
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- internal css -->
		<style>
			#mid_title {
				text-align: center;
			}
			#table_body, #table_head {
				text-align: center;
			}
			.card {
				margin-top: 50px;
			}
			.fake_body {
				padding-top: 100px;
			}
		</style>
	</head>
	<body>
	
		<div class="fake_body container">
			{% if user.is_authenticated %}
			<h1 class="mx-auto text-dark"> Halo {{user.first_name}}, ini adalah program yang telah anda donasikan </h1>
			{% endif %}
			<!-- <h1>test</h1> -->
			<div class="card bg-light text-dark shadow p-4 mb-4 bg-white">
				<div class="card-body">
					<table class="table table-striped table-responsive-md">
						<thead id="table_head">
							<tr>
								<th>Nama Program:</th>
								<th>Jumlah donasi:</th>
							</tr>	
							{% for i in data %}
							<tr>
								<td> {{i.program}} </td>
								<td> {{i.uang}} </td>
							</tr>
							{% endfor %}
						</thead>
	
	</body>
</hmtl>
{% endblock %}

Beranda/templates/home.html
{% extends 'base.html' %}
{% load static %}

        {% block content %}
        <body>

            <div class="content" id ="bg-img">
                
                <h1><b>Donasi Anda</b></h1>
                <p>adalah inspirasi orang lain</p>
                
                <div class="col-sm-1">
                    <a style="background: white; color:#598FB5; border-color: transparent;" type="button" class="btn btn-primary btn-lg" href="{% url 'donasi:donatur' %}"> DONATUR</a>
                    <br/>
                    <a style="background: white; color:#598FB5; border-color: transparent; margin-top: 20px;width: 90px;" type="button" class="btn btn-primary btn-lg" href="{% url 'program' %}"> PROGRAM  </a>
                </div>
                
            </div>

        </body>
        
    
{% endblock %}

Beranda/templates/index.html
<!DOCTYPE html>

<html>
    Hello world!
</html>

Beranda/templates/program.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body>
  <center>
  <h1>Siap memberi bantuan? </h1>
  <h3>Hallo! Pilih program yang ingin anda bantu :)</h3>
</center>
  <br/>
    <div class="container">
          <div class="card-columns">

              {% for i in programs %}
            <div class="card mb-4 shadow-sm">
              <img class="card-img-top" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="{{i.img_program}}" data-holder-rendered="true">
              <div class="card-body">
                <h4> {{i.judul_program}}<br/></h4>
                <p class="card-text">{{i.isi_program}}<br/><br/><br/></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    {% if user.is_authenticated %}
                    <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'donasi:program_donasi' id=i.id %}">Donasi</a>
                    {% else %}
                    <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'social:begin' 'google-oauth2' %}">Donasi</a>
                    {% endif %}
                  </div>
                </div>
              </div>
              
            </div>
            {% endfor %}

          </div>
    </div>
    
                  
</body>

{% endblock %}