TP1/urls.py
from django.contrib import admin

from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Beranda.urls')),
    path('', include('donasi.urls')),
    path('',include('daftar.urls')),
    path('',include('About.urls')),
    path('auth/', include('social_django.urls', namespace = 'social'))

]

donasi/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "donasi"

urlpatterns = [
    path('donatur/', donatur_view, name='donatur'),
    path('postdonasi/', formView, name='post'),
    path('thankyou/', thankyou, name='thankyou'),
    path('donasi/<int:id>/', donasi_view, name='program_donasi'),
]

donasi/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class MyModels(models.Model):
    program = models.CharField(max_length=30)
    nama = models.CharField(max_length=30)
    email = models.EmailField(max_length=100)
    uang = models.CharField(max_length =30)
    check = models.BooleanField(default=False)

    # def get_absolute_url(self):
    #     return reverse('index', kwargs={'id':self.id})

donasi/forms.py
from django import forms

class FormPage(forms.Form):

    # program = forms.CharField(label='Nama Program', max_length=30, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    # nama = forms.CharField(label='Nama Lengkap', max_length=30, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    # email = forms.EmailField(label='Email', max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    uang = forms.CharField(label='Jumlah Uang', max_length=30, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    check = forms.BooleanField(label = "Anonymous", required = False)

donasi/views.py
from django.shortcuts import render
from .models import MyModels
from .forms import FormPage
from Beranda.models import Program
from daftar.models import Pengguna
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def donasi_view(request, id):
    data = Program.objects.get(id=id)
    username = None
    if request.user.is_authenticated:
        username = request.user.username
    response = {'form': FormPage(),
                'data': data,
                'username': username}
    return render(request, "Donasi.html", response)

def donatur_view(request):
    result = MyModels.objects.all()
    response = {'result': result}
    return render(request, "Donatur.html", response)

def formView(request):
    response = {}
    donasi = FormPage(request.POST or None)
    if (request.method == 'POST' and donasi.is_valid()):
        response['program'] = request.POST['program']
        response['nama'] = request.user.username
        response['email'] = request.user.email
        response['uang'] = request.POST['uang']
        check = True if 'check' in request.POST else False
        donasi_form = MyModels(program = response['program'],
                               nama = response['nama'],
                               email = response['email'],
                               uang = response['uang'],
                               check = check)
        donasi_form.save()
        return HttpResponseRedirect('/thankyou/')
    else:
        return HttpResponseRedirect('/program/')

def thankyou(request):
    return render(request, "thankyou.html")

donasi/templates/Donasi.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-7">
            <div class="form">
                <form method="POST" action="{% url 'donasi:post' %}">
                {% if user.is_authenticated %}
                {% csrf_token %}
                <p> Nama Program : <span id="dataprogram">{{ data.judul_program }}</span></p>
                <p> Nama : <span id="datanama">{{username}}</span></p>
                <p> Email : <span id="dataemail">{{user.email}}</span></p>
                <p> Jumlah donasi : <span id="uwang">{{form.uang}}</span></p>
                <p> Anonymous {{form.check}} </p>
                <input type="hidden" name="program" value="{{data.judul_program}}">
                {% else %}
                {% csrf_token %}
                {{ form.as_p }}
                <input type="hidden" name="program" value="{{data.judul_program}}">
                {% endif %}
                <button class="btn btn-lg btn-primary sapmit" type="submit"> Submit </button>
                <br><br>
                </form>
            </div>
        </div>
        <div class="col-sm-5">
            <img src= "{% static 'data.jpg' %}" alt = "Picture can't be opened" width=80% height=70%>

        </div>
    </div>
</div>

{% endblock %}

donasi/templates/Donatur.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
        <h1 style="text-align: center">Pahlawan Kami</h1>
        <table class="table">
            <thead>
            <th>Program</th>
            <th>Nama</th>
            </thead>
            <tbody>
            {% for i in result %}
            {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
            <tr class="warning"> {% else %} <tr class="success">
                {% endif %}
                <td> {{i.program}} </td>
                {% if i.check %}
                    <td> Anon </td>
                {% else %}
                    <td> {{i.nama}} </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

donasi/templates/history_page.html
{% load static %}
<hmtl>
	<head>
		<!-- bootstrap using cdn -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<!-- responsive for mobile -->
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- internal css -->
		<style>
			#mid_title {
				text-align: center;
			}
			#table_body, #table_head {
				text-align: center;
			}
			.card {
				margin-top: 50px;
			}
			.fake_body {
				padding-top: 100px;
			}
		</style>
	</head>
	<body>
	{% include "layout/navbar.html" %}
		<div class="fake_body container">
			{% if user.is_authenticated %}
			<h1 class="mx-auto text-dark"> Halo {{user.first_name}}, ini adalah program yang telah anda donasikan </h1>
			{% endif %}
			<!-- <h1>test</h1> -->
			<div class="card bg-light text-dark shadow p-4 mb-4 bg-white">
				<div class="card-body">
					<table class="table table-striped table-responsive-md">
						<thead id="table_head">
							<tr>
								<th>No</th>
								<th>Program</th>
								<th>Jumlah Donasi</th>
							</tr>	
						</thead>
						<tbody id="table_body">
							<tr>
								<td>1</td>
								<td>Gempa Palu</td>
								<td>Rp. 1000.000 </td>
							</tr>
							<tr>
								<td>2</td>
								<td>Gempa Palu</td>
								<td>Rp. 1000.000 </td>
							</tr>
							<tr>
								<td>3</td>
								<td>Gempa Palu</td>
								<td>Rp. 1000.000 </td>
							</tr>
							<tr>
								<td>4</td>
								<td>Gempa Palu</td>
								<td>Rp. 1000.000 </td>
							</tr>
							<tr>
								<td>5</td>
								<td>Gempa Palu</td>
								<td>Rp. 1000.000 </td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	{% include "layout/footer.html"%}
	</body>
</hmtl>

donasi/templates/index.html
<!DOCTYPE html>

<html>
    Hello world!
</html>

donasi/templates/thankyou.html
{% extends 'base.html' %}
{% load static %}

        {% block content %}
        <body>

            <div class="content" id ="bg-img">
                
                <h1><b>Terima kasih</b></h1>
                <p>telah mendonasikan uang anda</p>
                
            </div>

        </body>
        
    
{% endblock %}